version: '3'
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sitekcode
      POSTGRES_DB: app_development
    ports: 
     - "5432:5432"
    volumes:
     - pgdata_test:/var/lib/postgresql/data
  app:
    build: .
    command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
    - .:/app
    ports:
     - "3000:3000"
    depends_on:
      - db
volumes:
  pgdata_test: