version: '3'
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sitekcode
      POSTGRES_DB: app_development
    ports: 
     - "5432:5432"
    volumes:
     - pgdata_test:/var/lib/postgresql/data
  app:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    command: /bin/bash -c -l "bundle exec foreman s"
    environment: 
      RAILS_ENV: development
    volumes:
      - ../:/app
      - node_modules:/app/node_modules
      - ../package.json:/app/package.json
    ports:
     - "3000:3000"
    depends_on:
      - db
volumes:
  pgdata_test:
  node_modules: